export enum IndicatorVariationStatus {
  CALCULATED = 'CALCULATED',
  NO_CURRENT_VALUE = 'NO_CURRENT_VALUE',
  NO_PREVIOUS_VALUE = 'NO_PREVIOUS_VALUE',
  PREVIOUS_VALUE_ZERO = 'PREVIOUS_VALUE_ZERO',
}
